name: Build and Release

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nim
        uses: iffy/install-nim@v5
      
      - name: Build executable
        run: nim c -d:release gnurdle.nim

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gnurdle-binary
          path: gnurdle

      - name: Create GitHub Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: gnurdle
